title: The Kingdom of Code
description: Kingdom of Code website
baseurl: ""
url: "https://thekingdomofcode.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
